# My information
name: Nasrudin Salim
email: Nas@NasrudinSalim.com
description_user: Data Scientist, Entrepreneur

# Social Media and profile
github: https://github.com/nasdin
# medium: https://medium.com
linkedin: https://www.linkedin.com/in/nasrudin-salim
#kaggle:
resume: https://docs.google.com/document/d/1nJC5Fedi9EwjB4b-V-5wD1fnw_8eqdrFlHUqf9EOC0I/
cv_online: http://cv.nasrudinsalim.com
blog: http://blog.nasrudinsalim.com

# Site information
title: Nasrudin Salim, Data Science Specialist & Expert
description: I specialize in Artificial Intelligence, Machine Learning, financial markets and fintech. I'm a Data Scientist, entrepreneur, a consultant and have managed other startups.
baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://nasrudinsalim.com/ #the url of your site
google_analytics_tracking_id: UA-106147156-4
cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.
#show_blog:

# SEO
keywords_SEO: Nasrudin, Nasrudin Salim, Nasrudin Bin Salim, Nasrudin Salim Suden, Nasdin, data science, data scientist, data engineer, trader, forex, machine learning, AI, artificial intelligence, supervised learning, unsupervised learning, reinforcement learning, deep learning, sql, databases, Nasdin94


cookie_accept_message: "Nasrudin: Thanks! <br> Nasrudin: Enjoy your stay!"

#Parallax images
parallax_image_one: assets/images/Nasrudin.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/Singapore.jpg

#Projects
projects:
  - title: First Project
    description: Describe your project!
    url: https://github.com/nasdin
    url_title: Github
    picture:
  - title: Second Project
    description: Describe your project!
    url: https://github.com/nasdin
    url_title: Github
    picture:
  - title: Third Project
    description: Describe your project!
    url: https://github.com/nasdin
    url_title: Github
    picture:
  - title: Fourth Project
    description: Describe your project!
    url: https://github.com/nasdin
    url_title: Github
    picture:

#For interesting things to add into a carousel in the future
#carousel:
#  - button: Github
#  - title:
#    description:
#    url:
#    picture:




# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: python
  - name: c
  - name: cplusplus
  - name: django
  - name: go
  - name: docker
  - name: git
  - name: github
  - name: mongodb
  - name: mysql
  - name: postgresql
  - name: amazonwebservices
  - name: pycharm
  - name: ubuntu
  - name: heroku

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons




# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
