## Loconotion Site Configuration File ##
# full .toml configuration example file to showcase all of Loconotion's available settings
# check out https://github.com/toml-lang/toml for more info on the toml format

# name of the folder that the site will be generated in
name = "Nasrudin_Salim"

# the notion.so page to being parsing from. This page will become the index.html
# of the generated site, and loconotion will parse all sub-pages present on the page
page = "https://nasrudinsalim.notion.site/Nasrudin-Salim-5b75cdda6a344171a535b9802af36adf?pvs=4"

# optionally apply notion's dark mode, remove the line below to use the default light mode
theme = "light"

## Global Site Settings ##
# this [site] table defines override settings for the whole site
# later on we will see how to define settings for a single page
[site]
  ## Custom Meta Tags ##
  # defined as an array of tables (double square brackets)
  # each key in the table maps to an atttribute in the tag
  # the following adds the tag <meta name="title" content="Loconotion Test Site"/>
  [[site.meta]]
  name = "title"
  content = "Nasrudin Salim | Impacting the future of humanity"
  [[site.meta]]
  name = "keywords"
  content = "Nasrudin Salim, Singapore, entrepreneur, blockchain, artificial intelligence, AI, startups, technology innovator, financial independence, tech investments"
  [[site.meta]]
  name = "description"
  content = "Unlock your potential with Nasrudin Salim, an expert specializing in AI, Blockchain, DeFi, Quantitative Trading, and strategic life advice. With an IQ in the genius range, Nasrudin offers bespoke consultations to navigate the complexities. Schedule your consultation today to transform your challenges into opportunities"

  ## Custom Fonts ##
  # you can specify the name of a google font to use on the site - use the font embed name
  # if in doubt select a style on fonts.google.com and navigate to the "embed" tag to
  # check the name under CSS rules
  # the following table keys controls the font of specific elements:
  #   site: changes the font for the whole page (apart from code blocks)
  #         but the settings below override it
  #   navbar: site breadcrumbs on the top-left of the page
  #   title: page title (under the icon)
  #   h1: heading blocks, and inline databases' titles
  #   h2: sub-heading blocks
  #   h3: sub-sub-heading blocks
  #   body: non-heading text on the page
  #   code: text inside code blocks
  [site.fonts]
   site = 'Intro'
   navbar = 'Intro'
   title = 'Intro'
  h1 = 'Canter'
  h2 = 'Canter'
  h3 = 'Canter'
  body = 'Komoda'
  code = 'Azonix'

  ## Custom Element Injection ##
  # defined as an array of tables [[site.inject]], followed by 'head' or 'body' to set
  # the injection point, followed by name of the tag to inject
  # each key in the table maps to an atttribute in the tag
  # e.g. the following injects this tag in the <head>:
  #   <link href="favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
  [[site.inject.head.link]]
   rel="icon"
   sizes="16x16"
   type="image/png"
   href="personal_site/nasicon.png"

  # the following injects this tag in the in the <body>:
  #   <script src="custom-script.js" type="text/javascript"></script>
  # note that all href / src files are copied to the root of the site folder
  # regardless of their original path
  # [[site.inject.body.script]]
  # type="text/javascript"
  # src="/example/custom-script.js"

  # the following injects this script in the <head>:
  #   <script>console.log("Hello, world!")</script>
  [[site.inject.body.script]]
  inner_html="""
  </script>
            <a href="https://taskade.com?via=ko8f7" target="_blank" style="outline:none;border:none;"><img src="https://d2gdx5nv84sdx2.cloudfront.net/uploads/ktbifmo1/marketing_asset/banner/12354/500_x_507.png" alt="taskade" border="0"/></a>
        <script>
   """

## Individual Page Settings ##
# the [pages] table defines override settings for individual pages, by defining
# a sub-table named after the page url (or part of the url, but careful about
# not using a string that appears in multiple page urls)
[pages]
  # the following settings will only apply to this page:
  #   https://www.notion.so/d2fa06f244e64f66880bb0491f58223d
   [pages.High-IQ-Societies-b17d50fa5592484897d781a470cbf3dd]
    ## custom slugs ##
    # inside page settings, you can change the url for that page with the 'slug' key
    # e.g. page "/d2fa06f244e64f66880bb0491f58223d" will now map to "/games-list"
    slug = "high-iq-societies"

    # change the description meta tag for this page only
   # [[pages.d2fa06f244e64f66880bb0491f58223d.meta]]
   # name = "description"
   # content = "A fullscreen list database page, now with a pretty slug"

    # change the title font for this page only
 #   [pages.d2fa06f244e64f66880bb0491f58223d.fonts]
   # title = 'DM Mono'

  # set up pretty slugs and options for the other database pages
 # [pages.54dab6011e604430a21dc477cb8e4e3a]
 #   slug = "film-gallery"

#  [pages.2604ce45890645c79f67d92833083fee]
   # slug = "books-table"

    # don't follow any link on the page, skipping parsing sub-pages linked from this one
    # useful for large tables where we don't want individual pages for each item
  #  no-links = true

#  [pages.a28dba2e7a67448da52f2cd2c641407b]
  #  slug = "random-board"
  #  no-links = true

# Sitemap configuration
# Remove if you don't want to generate sitemap.xml
protocol = "https"
domain = "nasrudinsalim.com"
remove_html_extension = true
